controller_manager:
  ros__parameters:
    update_rate: 50
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    # joint_broad:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    cmd_vel_timeout: 1.0

    publish_rate: 50.0

    base_frame_id: base_link
    odom_frame_id: odom

    left_wheel_names: ["base_to_wheel_back_left","base_to_wheel_front_left"]
    right_wheel_names: ["base_to_wheel_back_right","base_to_wheel_front_right"]
    wheel_separation: 0.34
    wheel_radius: 0.03

    use_stamped_vel: false

    open_loop: true

    # wheels_per_side: 2
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    # open_loop: false
    enable_odom_tf: true

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    linear.x.max_velocity: 10.0
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    angular.z.has_velocity_limits: true
    # angular.z.has_acceleration_limits: true
    # angular.z.has_jerk_limits: false
    angular.z.max_velocity: 10.0
    # angular.z.min_velocity: 6.0
    # angular.z.max_acceleration: 4.0
    # angular.z.min_acceleration: 6.0
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: 6.0

    # angular.z.has_velocity_limits: true
    # angular.z.has_acceleration_limits: true
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: 1.0
    # angular.z.min_velocity: -1.0
    # angular.z.max_acceleration: 1.0
    # angular.z.min_acceleration: -1.0
    # angular.z.max_jerk: 0.0
    # angular.z.min_jerk: 0.0


# joint_broad:
#   ros__parameters: